# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.cache/wt [current_project]
set_property parent.project_path C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/sources_1/imports/COMP541/Lab5/Lab6.srcs/sources_1/imports/Downloads/display640x480.sv
set_property file_type "Verilog Header" [get_files C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/sources_1/imports/COMP541/Lab5/Lab6.srcs/sources_1/imports/Downloads/display640x480.sv]
read_mem {
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/new/imem_screentest.mem
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/new/dmem_screentest.mem
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/new/smem_screentest.mem
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/new/bmem_screentest.mem
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/new/imem_screentest_pause.mem
}
read_verilog -library xil_defaultlib -sv {
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/sources_1/imports/COMP541/Lab9/Lab9.srcs/sources_1/imports/new/fulladder.sv
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/sources_1/imports/COMP541/Lab9/Lab9.srcs/sources_1/imports/new/add_sub_8bit.sv
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/sources_1/imports/COMP541/Lab3/Lab3.srcs/sources_1/new/shifter.sv
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/sources_1/imports/COMP541/Lab3/Lab3.srcs/sources_1/new/logical.sv
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/sources_1/imports/COMP541/Lab3/Lab3.srcs/sources_1/new/comparator.sv
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/sources_1/imports/COMP541/Lab3/Lab3.srcs/sources_1/new/addsub.sv
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/sources_1/imports/COMP541/Lab8/Lab8.srcs/sources_1/new/register_file.sv
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/sources_1/imports/COMP541/Lab3/Lab3.srcs/sources_1/new/ALU.sv
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/sources_1/imports/COMP541/Lab5/Lab6.srcs/sources_1/imports/new/xycounter.sv
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/new/soundregister.sv
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/sources_1/new/screenmemory.sv
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/new/lightregister.sv
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/sources_1/imports/sources_1/new/hexto7seg.sv
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/sources_1/new/dmem.sv
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/sources_1/imports/COMP541/Lab9/Lab9.srcs/sources_1/imports/new/datapath.sv
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/sources_1/imports/COMP541/Lab9/Lab9.srcs/sources_1/imports/new/controller.sv
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/sources_1/imports/COMP541/Lab5/Lab6.srcs/sources_1/new/vgatimer.sv
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/sources_1/new/bitmapmemory.sv
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/sources/montek_sound_Nexys4.sv
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/sources_1/imports/COMP541/Lab9/Lab9.srcs/sources_1/new/mips.sv
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/sources_1/new/memIO.sv
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/sources_1/imports/sources_1/new/keyboard.sv
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/sources_1/imports/new/imem.sv
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/sources_1/imports/sources_1/imports/new/display8digit.sv
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/sources_1/new/clockdivider_Nexys4.sv
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/sources_1/imports/COMP541/Lab5/Lab6.srcs/sources_1/imports/Downloads/vgadisplaydriver.sv
  C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/sources_1/imports/sources_1/new/top.sv
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/constrs_1/imports/new/clock.xdc
set_property used_in_implementation false [get_files C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/constrs_1/imports/new/clock.xdc]

read_xdc C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/constrs_1/imports/new/keyboard.xdc
set_property used_in_implementation false [get_files C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/constrs_1/imports/new/keyboard.xdc]

read_xdc C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/constrs_1/imports/new/vga.xdc
set_property used_in_implementation false [get_files C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/constrs_1/imports/new/vga.xdc]

read_xdc C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/constrs_1/imports/new/reset.xdc
set_property used_in_implementation false [get_files C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/constrs_1/imports/new/reset.xdc]

read_xdc C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/constrs_1/imports/new/led.xdc
set_property used_in_implementation false [get_files C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/constrs_1/imports/new/led.xdc]

read_xdc C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/constrs_1/imports/new/sound.xdc
set_property used_in_implementation false [get_files C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/constrs_1/imports/new/sound.xdc]

read_xdc C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/constrs_1/new/segdisplay.xdc
set_property used_in_implementation false [get_files C:/Users/Kishin/Documents/COMP541/Lab10PartC/Lab10PartC.srcs/constrs_1/new/segdisplay.xdc]


synth_design -top top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
